name: Prettier

permissions:
  contents: read
  pull-requests: write

on:
  merge_group:
    types: [checks_requested]
  pull_request:

jobs:
  prettier:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          ref: ${{ github.head_ref }}
          fetch-depth: 0

      # @v2
      - uses: oven-sh/setup-bun@22457c87c1b161cf7dde222c3e82b2b5f8d2bed2
      - run: bun install prettier

      - name: Prettify code
        run: bun prettier -c .

  test:
    runs-on: ubuntu-latest
    steps:
      - name: placeholder
        run: echo OK
