name: Prettier

permissions:
  contents: read
  pull-requests: write

on:
  merge_group:
    types: [checks_requested]
  pull_request:

jobs:
  prettier:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          ref: ${{ github.head_ref }}
          fetch-depth: 0

      - name: Prettify code
        uses: creyD/prettier_action@v4.6
        with:
          prettier_options: --no-config -c .
          only_changed: true

  test:
    runs-on: ubuntu-latest
    steps:
      - name: placeholder
        run: echo OK
